### ISSUE TITLE
在iOS Safari上默认显示为英语

### ISSUE THREAD

**Issue by solarhell** [thinkjs-team/cicada#15]
这个判断是 thinkjs this.lang 方法实现的 在这里还是这个方法吗

**Comment by lizheming** [comment]
判断应该和 ThinkJS 一样。我在 iOS Safari 隐私模式下测试了，是中文的诶，是系统的原因么？

**Comment by akira-cn** [comment]
现在是根据http.header里面的accept-language判断的，如果默认语言不是zh-CN的话，就是英文了，可以在src/common/middleware.js里面修改
