### ISSUE TITLE
你好,安装不成功,请求帮助

### ISSUE THREAD

**Issue by wasas** [thinkjs-team/cicada#20]
npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
extract:unzip → gunzTarPe ▐ ╢█████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░╟
Killed

我安装的时候, 有上面的提示,  
我的服务器是 centos 6.7
编译 node.js 0.12.13 版本无法安装本程序, 

下载编译好的 5.10.1 版本,安装就提示上面的了..
npm 版本是 3.8.3

看上面的提示,第一个和第三个好像是让我升级那两个东西, google 了好多种方法也没解决...

程序我是直接 wget 然后 unzip 解压的,用 vi 改过 pm2.json 中 cwd 的参数为当前目录. max_memory_restart 参数为 60M (我的VPS是个128M的小内存,不知道应不应该改这个)

**Comment by lizheming** [comment]
warning 是不用管的，你这个 Killed 是什么意思？是自己 Ctrl+C 了么？

**Comment by wasas** [comment]
没有... 都是她自己自动的.....
我测试过 thinkjs.org 推介的博客程序 Firekylin 是可以正常安装使用的..

我刚才又试了一下, 把所有程序都关掉, 内存还有 123M , 另外还有 50M 左右的缓存, 应该够安装这个了的吧..  还是一样的到这个进度条, 就自动 Killed 了...

看进度条前面的提示, extract:unzip → gunzTarPe 是程序要解压什么吧.. 为啥会自己 Killed 呢...
