### ISSUE TITLE
使用默认配置 sqlite3 数据库 ，删除收藏报错

### ISSUE THREAD

**Issue by shoyuf** [thinkjs-team/cicada#27]
https://github.com/thinkjs/cicada/blob/bd40d2b36884332b38a01c895cde29cb33ea7dda/src/home/controller/article.js#L165

删除报错
```json
{
  "errno": 1004,
  "errmsg": "删除失败"
}
```
但是查看数据库里面的snapshot和article 已经被删除了

调试 articleResult, snapshotResult 的结果分别为1 和 0

**Comment by lizheming** [comment]
可能底层库升级了导致返回数据的意义不对了，已经重新修改逻辑了，感谢反馈。
