### ISSUE TITLE
重新部署之后，用pm2启动会出错

### ISSUE THREAD

**Issue by niinaranpo** [thinkjs-team/cicada#3]
顺便问一下新版本怎么切换语言。。

**Comment by lizheming** [comment]
你直接运行一下 `node www/production.js` 看看有没有问题，如果没有问题应该就是你的 pm2 的配置有问题了吧。切换语言的话需要增加一个 `src/common/config/locale.js` 文件，并增加如下代码：

``` js
export default {
    default: "en"
};
```

**Comment by solarhell** [comment]
@niinaranpo see https://github.com/thinkjs-team/cicada/pull/4
